services:
  db:
    build: db
    restart: always
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    ports:
      - "${POSTGRES_PORT}:5432"
  api:
    build: api
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_SERVER
      - POSTGRES_PORT=5432
      - POSTGRES_DB
    ports:
      - "${GIS_API_PORT}:8000"

volumes:
  pgdata: